savedata: True
dataname: "Lorenz-100k"
lowmem: True
seqlen: 100000
n_series: 0 
series: ['Lorenz']
H: 100
alpha: 5
test_percent: 0.2
num_samples: 16 
batch_size: [256]
max_steps: [10000]
val_check_steps: [1000]
learning_rate: [1.e-3, 1.e-4]
n_pool_kernel_size: [[2,2,2], [4,2,1]]
n_freq_downsample: [[168, 24, 1], [24,12,1]]
n_blocks: [[1,1,1]]
mlp_units: [[[512,512],[512,512],[512,512]], [[1024, 1024], [1024, 1024], [1024, 1024]]]
interpolation_mode: ["linear"]

