lowmem: True
seqlen: 10000
n_series: 50
H: 300
alpha: 5
test_percent: 0.2
num_samples: 12 
batch_size: [256]
max_steps: [100000]
val_check_steps: [1000]
learning_rate: [1.e-3, 1.e-4]
n_pool_kernel_size: [[2,2,2], [4,2,1]]
n_freq_downsample: [[96,24,1],[24,12,1],[4,2,1]]
n_blocks: [[1,1,1]]
mlp_units: [[[1024,1024],[1024,1024],[1024,1024]]]
interpolation_mode: ["linear"]

