savedata: True 
dataname: "Lorenz-25x10000"
lowmem: True
dataset: 'Lorenz_25x10000_ic-0.02.csv'
H: 100
alpha: 5
test_percent: 0.1
num_samples: 4 
batch_size: [512]
max_steps: [10000]
val_check_steps: [1000]
learning_rate: [1.e-3]
n_pool_kernel_size: [[2,2,2], [4,2,1]]
n_freq_downsample: [[168, 24, 1], [24,12,1]]
n_blocks: [[1,1,1]]
mlp_units: [[[1024, 1024], [1024, 1024], [1024, 1024]]]
interpolation_mode: ["linear"]

