dataset: 'Lorenz_100x10000_ic-0.01-v2'
n_series_val: 5 
n_series_test: 5
H: 300
alpha: 5
num_samples: 1 
batch_size: [256, 512]
max_steps: [100000]
val_check_steps: [5000]
learning_rate: [1.e-4]
num_lr_decays: [6]
lr_decay_gamma: [0.5]

#three-stack configs
#stack_types: [['identity', 'identity', identity']]
#n_pool_kernel_size: [[2,2,2], [4,2,1]]
#n_freq_downsample: [[168, 24, 1], [24,12,1]]
#n_blocks: [[1,1,1]]
#mlp_units: [[[1024, 1024], [1024, 1024], [1024, 1024]]]

#four-stack configs
stack_types: [['identity', 'identity', 'identity', 'identity']]
n_pool_kernel_size: [[9,4,2,1]]
n_freq_downsample: [[180, 25, 6, 1]]
n_blocks: [[1,1,1,1]]
mlp_units: [[[2048,2048],[2048,2048],[2048,2048],[2048,2048]]]
interpolation_mode: ["linear"]

